#pragma once
#include "gpio.h"
#include "models.h"
#include <xparameters.h>


#define MODEL_CONFIGURATOR_ADDR XPAR_DATALINK_CONFIGURATOR_DATA_LINK_CONFIGURAT_0_BASEADDR

#define MODEL_GENERATOR_ADDR XPAR_DATALINK_GENERATOR_DATA_LINK_GENERATOR_1_BASEADDR

#define MODEL_ANALYZER_ADDR XPAR_DATALINK_ANALYZER_DATA_LINK_ANALYZER_1_BASEADDR

#define MODEL_4_ADDR ((mod4_t*)XPAR_DATALINK_ANALYZER_DATA_LINK_ANALYZER_4_BASEADDR)

#define MODEL_5_ADDR ((mod5_t*)XPAR_DATALINK_ANALYZER_DATA_LINK_ANALYZER_5_BASEADDR)


